### PR TITLE
windows python 3.9.2 deepcell install problem resolved

### LINKED ISSUE #85: pip install deepcell in windows 10 problem
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pishp\\AppData\\Local\\Temp\\pip-install-cbcuk0w4\\pathlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\pishp\\AppData\\Local\\Temp\\
pip-install-cbcuk0w4\\pathlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\pishp\AppData\Local\Temp\pip-pip-egg-info-f70xy34i'
         cwd: C:\Users\pishp\AppData\Local\Temp\pip-install-cbcuk0w4\pathlib\
    Complete output (39 lines):
    running egg_info
    creating C:\Users\pishp\AppData\Local\Temp\pip-pip-egg-info-f70xy34i\pathlib.egg-info
    writing C:\Users\pishp\AppData\Local\Temp\pip-pip-egg-info-f70xy34i\pathlib.egg-info\PKG-INFO
    writing dependency_links to C:\Users\pishp\AppData\Local\Temp\pip-pip-egg-info-f70xy34i\pathlib.egg-info\dependency_links.txt
    writing top-level names to C:\Users\pishp\AppData\Local\Temp\pip-pip-egg-info-f70xy34i\pathlib.egg-info\top_level.txt
    writing manifest file 'C:\Users\pishp\AppData\Local\Temp\pip-pip-egg-info-f70xy34i\pathlib.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\pishp\AppData\Local\Temp\pip-install-cbcuk0w4\pathlib\setup.py", line 6, in <module>
        setup(
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools\command\egg_info.py", line 297, in run
        self.find_sources()
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools\command\egg_info.py", line 304, in find_sources
        mm.run()
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools\command\egg_info.py", line 535, in run
        self.add_defaults()
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools\command\egg_info.py", line 575, in add_defaults
        rcfiles = list(walk_revctrl())
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools\command\sdist.py", line 20, in walk_revctrl
        for item in ep.load()(dirname):
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools_scm\integration.py", line 69, in find_files
        for ep in iter_entry_points("setuptools_scm.files_command"):
      File "c:\my_pack\up\\microservices\ms-job-manager\.cell_seg\deepcell_cellseg\lib\site-packages\setuptools_scm\utils.py", line 147, in iter_entry_points
        all_eps = entry_points()
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 562, in entry_points
        ordered = sorted(eps, key=by_group)
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 560, in <genexpr>
        dist.entry_points for dist in distributions())
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 261, in entry_points
        return EntryPoint._from_text(self.read_text('entry_points.txt'))
      File "C:\Users\pishp\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 511, in read_text
        return self._path.joinpath(filename).read_text(encoding='utf-8')
    AttributeError: 'WindowsPath' object has no attribute 'read_text'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

resolved here
https://github.com/zverozabr/deepcell-tracking/commit/4a8708a3bdbfdf6e4691347c52b80b1aef198438

### PR DESCRIPTION
**Pull request by zverozabr**
problem in https://github.com/vanvalenlab/deepcell-tracking/issues/85 

(Fixes #85)

### CODE REVIEW

**Comment by willgraf** [comment]
It looks like [pathlib2 is no longer supported](https://pypi.org/project/pathlib2/), so I'm not sure that this is the best fix for the issue. Maybe we can just pin the version of `pathlib` to prevent the breaking change in the latest release? (I'm assuming that the problem is a new release issue).

**Comment by zverozabr** [comment]
pathlib is included in python, but for compatibility with old versions, I added the latest version that I found, in general, you can remove it altogether from the setup

**Comment by zverozabr** [comment]
okay may be it only my problem, but this fix help me to install deepcell==0.11.0

**Comment by willgraf** [comment]
Great, thanks for the change - it seems `pathlib2` would have been fine to leave included, but since `pathlib` is now included in Python 3.4+ (and only Python 3.6+ is supported), there is no good reason to include it in `setup.py`.

I think this is also the cause of build failures in `deepcell-tf`. I'm not quite sure what the root cause is, but this looks to be a good fix.

**Pull request merged**
